from __future__ import annotations
from datetime import datetime, timezone
from typing import Any
from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column
from ..database import Base
def now(): return datetime.now(timezone.utc)
class Incident(Base):
    __tablename__="incidents"; id:Mapped[int]=mapped_column(primary_key=True); title:Mapped[str]=mapped_column(String(200)); description:Mapped[str]=mapped_column(Text,default=""); severity:Mapped[str]=mapped_column(String(20),default="SEV2"); source:Mapped[str]=mapped_column(String(50),default="demo"); service_name:Mapped[str]=mapped_column(String(100),default="sentinel-shop"); status:Mapped[str]=mapped_column(String(30),default="active"); started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); detected_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); resolved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); current_state:Mapped[str]=mapped_column(String(40),default="NEW"); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class EvidenceItem(Base):
    __tablename__="evidence_items"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); evidence_type:Mapped[str]=mapped_column(String(30)); source:Mapped[str]=mapped_column(String(255)); content:Mapped[str]=mapped_column(Text); summary:Mapped[str]=mapped_column(Text); timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); relevance_score:Mapped[float]=mapped_column(Float,default=0.5); metadata_json:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict)
class Hypothesis(Base):
    __tablename__="hypotheses"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); title:Mapped[str]=mapped_column(String(250)); explanation:Mapped[str]=mapped_column(Text); evidence_for:Mapped[list]=mapped_column(JSON); evidence_against:Mapped[list]=mapped_column(JSON); confidence:Mapped[float]=mapped_column(Float); rank:Mapped[int]=mapped_column(Integer); status:Mapped[str]=mapped_column(String(30),default="proposed")
class ReproductionAttempt(Base):
    __tablename__="reproduction_attempts"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); command:Mapped[str]=mapped_column(Text); test_file:Mapped[str]=mapped_column(Text); result:Mapped[str]=mapped_column(String(30)); stdout:Mapped[str]=mapped_column(Text,default=""); stderr:Mapped[str]=mapped_column(Text,default=""); duration:Mapped[float]=mapped_column(Float,default=0); exit_code:Mapped[int]=mapped_column(Integer)
class PatchCandidate(Base):
    __tablename__="patch_candidates"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); hypothesis_id:Mapped[int]=mapped_column(ForeignKey("hypotheses.id")); diff:Mapped[str]=mapped_column(Text); explanation:Mapped[str]=mapped_column(Text); files_changed:Mapped[list]=mapped_column(JSON); risk_score:Mapped[float]=mapped_column(Float); status:Mapped[str]=mapped_column(String(30),default="proposed")
class VerificationRun(Base):
    __tablename__="verification_runs"; id:Mapped[int]=mapped_column(primary_key=True); patch_candidate_id:Mapped[int]=mapped_column(ForeignKey("patch_candidates.id")); test_type:Mapped[str]=mapped_column(String(40)); command:Mapped[str]=mapped_column(Text); passed:Mapped[bool]=mapped_column(Boolean); stdout:Mapped[str]=mapped_column(Text,default=""); stderr:Mapped[str]=mapped_column(Text,default=""); duration:Mapped[float]=mapped_column(Float,default=0); exit_code:Mapped[int]=mapped_column(Integer)
class ApprovalRequest(Base):
    __tablename__="approval_requests"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); requested_action:Mapped[str]=mapped_column(String(100)); summary:Mapped[str]=mapped_column(Text); risk_level:Mapped[str]=mapped_column(String(20)); approved:Mapped[bool|None]=mapped_column(Boolean); approved_by:Mapped[str|None]=mapped_column(String(100)); approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class AuditEvent(Base):
    __tablename__="audit_events"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); event_type:Mapped[str]=mapped_column(String(80)); actor:Mapped[str]=mapped_column(String(100)); input_json:Mapped[dict]=mapped_column(JSON,default=dict); output_json:Mapped[dict]=mapped_column(JSON,default=dict); timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class PullRequestRecord(Base):
    __tablename__="pull_request_records"; id:Mapped[int]=mapped_column(primary_key=True); incident_id:Mapped[int]=mapped_column(ForeignKey("incidents.id")); branch_name:Mapped[str]=mapped_column(String(150)); commit_sha:Mapped[str]=mapped_column(String(64)); title:Mapped[str]=mapped_column(String(250)); description:Mapped[str]=mapped_column(Text); diff:Mapped[str]=mapped_column(Text); status:Mapped[str]=mapped_column(String(30),default="draft"); external_url:Mapped[str|None]=mapped_column(String(500))
