import {useEffect,useMemo,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Activity,Archive,CheckCircle2,CircleDot,Download,GitBranch,GitPullRequest,Network,Play,RotateCcw,Shield,ShieldCheck,Swords,TriangleAlert,Zap} from 'lucide-react';
import {api} from './api/client';
import {ApprovalCard} from './components/ApprovalCard';
import type {BlastRadius,CandidateCheck,Incident,RepairCandidate,ScenarioResult,Tournament,TwinManifest} from './types';

const FLOW=[['Trigger incident','start'],['Collect evidence','collect-evidence'],['Rank hypotheses','generate-hypotheses'],['Build twin + replay','reproduce'],['Generate 3 candidates','generate-patch'],['Run tournament','verify']] as const;
const SCREEN_STATES:Record<string,string>={healthy:'NEW',incident:'ALERT_RECEIVED',evidence:'EVIDENCE_READY',hypothesis:'HYPOTHESES_READY',twin:'REPRODUCTION_CONFIRMED',reproduced:'REPRODUCTION_CONFIRMED',tournament:'PATCH_READY',counterfactual:'PATCH_READY','blast-radius':'VERIFICATION_PASSED',verified:'VERIFICATION_PASSED',approval:'AWAITING_APPROVAL',completed:'COMPLETED'};
const SCREEN_STAGE:Record<string,number>={healthy:0,incident:1,evidence:2,hypothesis:3,twin:4,reproduced:5,tournament:6,counterfactual:7,'blast-radius':8,verified:8,approval:9,completed:10};
const fixtureIncident=(state:string):Incident=>state==='healthy'
 ? {id:900,title:'Sentinel Shop healthy baseline',description:'Checkout availability 100% · error rate 0% · no active incident',severity:'INFO',status:'resolved',current_state:'NEW',created_at:'2026-07-20T12:04:00Z'}
 : {id:900,title:'Discount + TN tax causes checkout 500',description:'SAVE10 orders in TN fail during nullable tax arithmetic',severity:'SEV1',status:'active',current_state:SCREEN_STATES[state]||'ALERT_RECEIVED',created_at:'2026-07-20T12:04:00Z'};
const fixtureCandidates:RepairCandidate[]=[
 {candidate_id:'candidate-a',rationale:'Minimal discount-path fallback',files_changed:['demo_app/app/main.py'],lines_added:1,lines_removed:1,known_risks:['TN without discount still fails'],diff:'conditional null fallback',score:84.2,eligible:false,recommendation_reason:'False fix detected in a nearby input.'},
 {candidate_id:'candidate-b',rationale:'Boundary validation',files_changed:['demo_app/app/main.py','demo_app/app/validation.py'],lines_added:14,lines_removed:2,known_risks:['Changes public API contract'],diff:'return 422 for missing rate',score:78.6,eligible:false,recommendation_reason:'Integration gate failed; blast radius is larger.'},
 {candidate_id:'candidate-c',rationale:'Normalize nullable rate at arithmetic boundary',files_changed:['demo_app/app/main.py'],lines_added:1,lines_removed:1,known_risks:['Production policy may prefer fail-closed'],diff:'taxable * (rate or Decimal("0"))',score:97.1,eligible:true,recommendation_reason:'All mandatory gates and nearby scenarios pass; smallest estimated blast radius.'}
];
const gates=['regression','unit','integration','ruff','mypy','bandit','fault_injection','performance','api_contract','dependency_impact','security_policy','replay_determinism'];
const fixtureChecks:CandidateCheck[]=fixtureCandidates.flatMap(c=>gates.map(g=>({candidate_id:c.candidate_id,gate:g,mandatory:gates.indexOf(g)<6,passed:c.candidate_id==='candidate-c'||(!['integration','api_contract'].includes(g)),reduced_assurance:['fault_injection','dependency_impact'].includes(g),duration_ms:40,details:'Deterministic twin check',evidence_ids:[1,2,3,4]})));
const fixtureBlasts:BlastRadius[]=[['candidate-a',34],['candidate-b',68],['candidate-c',18]].map(([id,score])=>({candidate_id:String(id),score:Number(score),confidence_label:'Moderate',modified_components:['checkout.calculate_tax'],transitive_components:['checkout workflow'],covered_workflows:['TN + SAVE10'],uncovered_workflows:['external settlement'],customer_impact:'Estimated checkout-path impact',graph_json:{nodes:[{id:'checkout',type:'endpoint'},{id:'tax',type:'function'},{id:'orders',type:'workflow'},{id:'test',type:'test'}],edges:[{from:'checkout',to:'tax',type:'calls'},{from:'tax',to:'orders',type:'affects'},{from:'test',to:'tax',type:'covers'}]}}));
const fixtureScenarios:ScenarioResult[]=['original','tn-no-discount','ga-save10','missing-no-discount','high-traffic','slow-dependency','database-outage','compound'].flatMap(s=>['original','candidate-a','candidate-b','candidate-c'].map(c=>{let outcome:'pass'|'fail'|'degraded'='pass';if(s==='database-outage')outcome='fail';else if(['slow-dependency','compound'].includes(s))outcome='degraded';else if(c==='original'&&s==='original')outcome='fail';else if(c==='candidate-a'&&s==='tn-no-discount')outcome='fail';else if(c==='candidate-b'&&['original','tn-no-discount','missing-no-discount'].includes(s))outcome='fail';return{scenario_id:s,candidate_id:c,outcome,latency_ms:outcome==='degraded'?1800:42,candidate_success:outcome!=='fail',new_failure:c!=='original'&&outcome==='fail'&&!['database-outage'].includes(s),confidence_label:'High',evidence_ids:[1,2]}}));
const fixtureTournament: Tournament={candidates:fixtureCandidates,checks:fixtureChecks,blast_radius:fixtureBlasts,red_team:fixtureCandidates.map(c=>({candidate_id:c.candidate_id,advocate_case:c.rationale,challenges:[{question:'Does this fail under nearby inputs?',result:c.eligible?'pass':'fail',linked_check:'api_contract',evidence_ids:[1,2]}],deterministic_verdict:c.eligible?'eligible':'ineligible'})),recommended_candidate:fixtureCandidates[2],weights:{regression_success:.25,unit_and_integration_success:.15,security_score:.1,static_quality_score:.1,replay_determinism:.1,performance_score:.1,blast_radius_score:.1,patch_minimality:.05,evidence_completeness:.05}};
const fixtureTwin:TwinManifest={twin_id:'twin-1-6be81bca91',source_commit:'074497caeaf30bbb',runtime_version:'3.12.8',operating_system:'Linux isolated runner',dependency_lock_hash:'91a7…3fd2',configuration_hash:'638c…9fe0',input_fixture_hash:'fde2…743c',random_seed:20260720,network_policy:'disabled',resource_limits:{cpu:1,memory_mb:512,pids:128},command_allowlist:['pytest','ruff','mypy','bandit','git'],protected_paths:['.env','.github/','policies/','sandbox/'],evidence_ids:[1,2,3,4],environment_fingerprint:'71ba…6e82',manifest_hash:'6be81bca91c8…a0e4'};

export default function App(){
 const qc=useQueryClient();const demoState=new URLSearchParams(location.search).get('demoState')||'';const screenshot=!!demoState;
 const demoStage=SCREEN_STAGE[demoState]??0;
 const incidents=useQuery({queryKey:['incidents'],queryFn:async()=>{const rows=await api.incidents();if(rows.length)return rows;await api.seed();return api.incidents()},enabled:!screenshot,retry:1});
 const rows=screenshot?[fixtureIncident(demoState)]:incidents.data||[];const [selected,setSelected]=useState<number>();const [running,setRunning]=useState(false);const [runError,setRunError]=useState('');
 useEffect(()=>{if(!selected&&rows[0])setSelected(rows.find(x=>x.title.includes('Discount + TN'))?.id||rows[0].id)},[rows,selected]);
 const live=useQuery({queryKey:['incident',selected],queryFn:()=>api.get(selected!),enabled:!!selected&&!screenshot,refetchInterval:2000});const incident=screenshot?rows[0]:live.data;
 const enabled=!!selected&&!screenshot;const evidence=useQuery({queryKey:['evidence',selected],queryFn:()=>api.evidence(selected!),enabled});const hypotheses=useQuery({queryKey:['hypotheses',selected],queryFn:()=>api.hypotheses(selected!),enabled});const timeline=useQuery({queryKey:['timeline',selected],queryFn:()=>api.timeline(selected!),enabled});const twin=useQuery({queryKey:['twin',selected],queryFn:()=>api.twin(selected!),enabled,retry:false});const replays=useQuery({queryKey:['replays',selected],queryFn:()=>api.replays(selected!),enabled,retry:false});const tournament=useQuery({queryKey:['tournament',selected],queryFn:()=>api.tournament(selected!),enabled,retry:false});const scenarios=useQuery({queryKey:['counterfactuals',selected],queryFn:()=>api.counterfactuals(selected!),enabled,retry:false});const links=useQuery({queryKey:['evidence-links',selected],queryFn:()=>api.evidenceLinks(selected!),enabled,retry:false});const scorecard=useQuery({queryKey:['scorecard',selected],queryFn:()=>api.scorecard(selected!),enabled,retry:false});const pkg=useQuery({queryKey:['package',selected],queryFn:()=>api.auditPackage(selected!),enabled,retry:false});const health=useQuery({queryKey:['health'],queryFn:api.health,enabled:!screenshot,refetchInterval:5000});
 const dataTournament=screenshot?(demoStage>=6?fixtureTournament:undefined):(tournament.data&&Array.isArray(tournament.data.candidates)?tournament.data:undefined);const dataTwin=screenshot?(demoStage>=4?fixtureTwin:undefined):(twin.data&&typeof twin.data.twin_id==='string'?twin.data:undefined);const dataScenarios=screenshot?(demoStage>=7?fixtureScenarios:[]):(Array.isArray(scenarios.data)?scenarios.data:[]);
 const refresh=()=>qc.invalidateQueries();const action=useMutation({mutationFn:({a,b}:{a:string;b?:object})=>api.action(selected!,a,b),onSuccess:refresh});const reset=useMutation({mutationFn:api.reset,onSuccess:async()=>{setSelected(undefined);await qc.invalidateQueries()}});
 const autonomous=async()=>{if(!incident||running||screenshot)return;setRunning(true);setRunError('');try{for(const [,endpoint] of FLOW){const current=await api.get(incident.id);if(endpoint==='start'&&current.current_state!=='NEW')continue;await api.action(incident.id,endpoint);await qc.invalidateQueries()} }catch(e){setRunError(e instanceof Error?e.message:'Investigation failed')}finally{setRunning(false);refresh()}};
 const state=incident?.current_state||'NEW';const progressed=!['NEW','ALERT_RECEIVED'].includes(state);const reproducibility=screenshot?(demoStage>=5?100:0):replays.data?.length?Math.round(100*new Set(replays.data.map(x=>x.deterministic_hash)).size/replays.data.length):0;const winner=dataTournament?.recommended_candidate;const winnerBlast=dataTournament?.blast_radius.find(x=>x.candidate_id===winner?.candidate_id)?.score;
 const scenarioNames=[...new Set(dataScenarios.map(x=>x.scenario_id))];const candidateCols=['original','candidate-a','candidate-b','candidate-c'];
 const kpis=[['SEVERITY',incident?.severity||'—'],['ROOT CAUSE',progressed?'High*':'Pending'],['REPRODUCIBILITY',`${reproducibility}%`],['CANDIDATES',String(dataTournament?.candidates.length||0)],['BLAST RADIUS',winnerBlast===undefined?'Pending':`${winnerBlast}/100`],['EVIDENCE',`${screenshot?100:links.data?.length?100:0}% linked`],['APPROVAL',state==='AWAITING_APPROVAL'?'Required':state==='COMPLETED'?'Approved':'Pending'],['DEPLOYMENT','NOT DEPLOYED']];
 if(incidents.isError&&!screenshot)return <div className="error-state"><h1>Backend connection failed</h1><p>Run <code>make demo</code>, verify port 8000, then retry.</p><button onClick={()=>incidents.refetch()}>Retry connection</button></div>;
 return <div className="app finale"><aside><div className="brand"><ShieldCheck/><b>SENTINEL<span>OPS</span></b></div><div className="twin-tag">RELIABILITY DIGITAL TWIN</div><div className={`ready ${screenshot||health.data?.ready?'ok':''}`}><i/>{screenshot||health.data?.ready?'SYSTEM READY':'CHECKING SERVICES'}</div><p className="eyebrow">INCIDENTS</p>{rows.map(x=><button className={`incident ${x.id===selected?'active':''}`} key={x.id} onClick={()=>setSelected(x.id)}><em>{x.severity}</em><strong>{x.title}</strong><small>{x.current_state.replaceAll('_',' ')}</small></button>)}<nav>{['command','timeline','evidence','hypotheses','twin','replay','tournament','counterfactual','blast','verification','approval','audit','scorecard'].map(x=><a href={`#${x}`} key={x}>{x.replaceAll('-',' ')}</a>)}</nav><button className="utility" onClick={()=>reset.mutate()} disabled={screenshot}><RotateCcw/> Reset Demo</button></aside><main><header id="command"><div><p className="eyebrow">AUTONOMOUS RELIABILITY ENGINEER</p><h1>Incident Command Center</h1></div><div className="live"><i/> LIVE · MOCK · {screenshot?'SAFE':health.data?.sandbox_mode?.toUpperCase()||'SAFE'}</div></header>{!incident?<Empty text="Preparing deterministic incident…"/>:<><section className="hero"><div><span className="sev"><TriangleAlert size={15}/>{incident.severity}</span><h2>{incident.title}</h2><p>{incident.description}</p><small>State <b>{state.replaceAll('_',' ')}</b> · Automatic deployment disabled</small></div><button className="primary" onClick={autonomous} disabled={running||screenshot||state==='AWAITING_APPROVAL'}>{running?'Investigating…':'Run Autonomous Investigation'} <Zap size={17}/></button></section>{runError&&<div className="error-state">{runError}</div>}<div className="kpi-grid">{kpis.map(([k,v])=><Kpi key={k} title={k} value={v} danger={k==='DEPLOYMENT'}/>)}</div>
 <Panel id="timeline" icon={<Activity/>} title="Incident Timeline" subtitle="Persisted state transitions and evidence arrival"><div className="timeline">{(screenshot?[{event_type:'evidence.collected',actor:'agent'},{event_type:'twin.replay.confirmed',actor:'sandbox'},{event_type:'tournament.completed',actor:'policy'}]:timeline.data||[]).slice(-8).map((x:any,i)=><div className="timeline-row" key={i}><i/><b>{x.event_type}</b><span>{x.actor}</span><button>Show evidence</button></div>)}</div></Panel>
 <div className="two"><Panel id="evidence" icon={<Network/>} title="Causal Evidence Graph" subtitle="Claims remain traceable; confidence labels are not calibrated probabilities"><div className="evidence-graph"><Node kind="symptom" label="HTTP 500"/><b>→</b><Node kind="telemetry" label="TypeError trace"/><b>→</b><Node kind="source" label="Nullable TN rate"/><b>→</b><Node kind="test" label="3× replay"/><b>→</b><Node kind="decision" label="Candidate C"/></div><div className="claim-list">{(screenshot?[{claim:'Nullable TN tax rate caused discounted arithmetic failure.',confidence_label:'High',evidence_ids:[1,2,3,4],missing_evidence:[]}]:links.data||[]).map((x:any,i)=><div key={i}><span className="confidence">{x.confidence_label}</span><b>{x.claim}</b><small>{x.evidence_ids.length} linked artifacts · Missing: {x.missing_evidence?.join(', ')||'none'}</small><button>Show evidence</button></div>)}</div></Panel><Panel id="hypotheses" icon={<CircleDot/>} title="Hypothesis Board" subtitle="Ranked, falsifiable, evidence for and against"><div className="hyp-list">{(screenshot?[{rank:1,title:'Nullable TN tax rate',confidence:.94,evidence_for:['Trace points to Decimal × None','TN configuration is null'],evidence_against:['Other regions succeed']},{rank:2,title:'Discount calculation defect',confidence:.42,evidence_for:['SAVE10 is present'],evidence_against:['SAVE10 works outside TN']}]:hypotheses.data||[]).map((h:any)=><article key={h.rank}><header><b>#{h.rank} {h.title}</b><span>{h.confidence>=.8?'High':h.confidence>=.5?'Moderate':'Low'}</span></header><p>For: {h.evidence_for.join(' · ')}</p><p className="against">Against: {h.evidence_against.join(' · ')||'No contradiction recorded'}</p><small>Falsification: replay with region and discount independently varied</small></article>)}</div></Panel></div>
 <Panel id="twin" icon={<GitBranch/>} title="Reliability Digital Twin" subtitle="Immutable manifest shared by every candidate"><>{dataTwin?<div className="manifest"><Kpi title="TWIN ID" value={dataTwin.twin_id}/><Kpi title="SOURCE COMMIT" value={dataTwin.source_commit.slice(0,12)}/><Kpi title="RANDOM SEED" value={String(dataTwin.random_seed)}/><Kpi title="NETWORK" value={dataTwin.network_policy.toUpperCase()} danger/><Kpi title="MANIFEST HASH" value={dataTwin.manifest_hash.slice(0,16)+'…'}/><Kpi title="RESOURCE LIMIT" value={`${dataTwin.resource_limits.cpu} CPU · ${dataTwin.resource_limits.memory_mb} MB`}/></div>:<Empty text="Twin is created after deterministic reproduction."/>}</></Panel>
 <Panel id="replay" icon={<Play/>} title="Replay Studio" subtitle="Three attempts under the same manifest and seed"><div className="replay-grid">{[1,2,3].map(n=><article key={n}><span>ATTEMPT {n}</span><b>{reproducibility===100?'HTTP 500 REPRODUCED':'Pending'}</b><small>48 ms · exit 1 · hash 70c9…ff2a</small></article>)}<article className="score"><span>REPRODUCIBILITY SCORE</span><strong>{reproducibility}%</strong><small>identical reproductions / attempts</small></article></div></Panel>
 <Panel id="tournament" icon={<Swords/>} title="Repair Tournament" subtitle="Identical twin · failed mandatory gate = ineligible"><div className="leaderboard">{(dataTournament?.candidates||[]).sort((a,b)=>b.score-a.score).map((c,i)=><article className={`${c.eligible?'winner':''}`} key={c.candidate_id}><div className="rank">{i+1}</div><div><span>{c.candidate_id.toUpperCase()}</span><h3>{c.rationale}</h3><p>{c.recommendation_reason}</p><small>{c.lines_added+c.lines_removed} changed lines · {c.files_changed.length} file(s)</small></div><div className="candidate-score"><strong>{c.score}</strong><em>{c.eligible?'ELIGIBLE':'DISQUALIFIED'}</em></div></article>)}</div><div className="gate-matrix"><div/><div>A</div><div>B</div><div>C</div>{gates.map(g=><div className="gate-row" key={g}><b>{g.replaceAll('_',' ')}</b>{['candidate-a','candidate-b','candidate-c'].map(c=>{const pass=dataTournament?.checks.find(x=>x.candidate_id===c&&x.gate===g)?.passed;return <span className={pass?'pass':'fail'} key={c}>{pass?'✓':'×'}</span>})}</div>)}</div></Panel>
 <Panel id="counterfactual" icon={<Zap/>} title="Counterfactual Lab" subtitle="What if the region, discount, dependency, or traffic conditions changed?"><div className="scenario-controls"><label>Region<select defaultValue="TN"><option>TN</option><option>GA</option><option>CA</option></select></label><label>Discount<select defaultValue="SAVE10"><option>SAVE10</option><option>None</option></select></label><label>Tax rate<select defaultValue="absent"><option value="absent">Absent</option><option>Present</option></select></label><label>Traffic<input type="range" min="1" max="500" defaultValue="1"/></label></div><div className="scenario-table"><div className="scenario-head"><b>Scenario</b>{candidateCols.map(c=><b key={c}>{c.replace('candidate-','')}</b>)}</div>{scenarioNames.map(s=><div className="scenario-row" key={s}><span>{s.replaceAll('-',' ')}</span>{candidateCols.map(c=>{const r=dataScenarios.find(x=>x.scenario_id===s&&x.candidate_id===c);return <i className={r?.outcome||'uncertain'} key={c}>{r?.outcome||'uncertain'}</i>})}</div>)}</div></Panel>
 <div className="two"><Panel id="blast" icon={<Network/>} title="Blast Radius" subtitle="Transparent estimate, not certainty"><div className="blast-list">{(dataTournament?.blast_radius||[]).map(x=><article className={x.candidate_id===winner?.candidate_id?'winner':''} key={x.candidate_id}><b>{x.candidate_id.toUpperCase()}</b><strong>{x.score}/100</strong><progress value={x.score} max="100"/><small>{x.confidence_label} confidence · {x.customer_impact}</small></article>)}</div><div className="impact-graph"><Node kind="endpoint" label="POST /checkout"/><b>→</b><Node kind="function" label="calculate_tax"/><b>→</b><Node kind="workflow" label="order total"/><b>←</b><Node kind="test" label="regression"/></div></Panel><Panel id="verification" icon={<Shield/>} title="Adversarial Review" subtitle="Advocate case · red-team case · deterministic verdict"><div className="review"><b>Advocate</b><p>{winner?.rationale||'Pending candidate evaluation.'}</p><b>Red team</b><p>Challenge symptom masking, API contract drift, nearby inputs, security defaults, performance, protected paths, and test strength.</p><b>Verdict</b><p className="ok-text">Candidate C eligible. A and B rejected by deterministic gates.</p></div></Panel></div>
 <section id="approval"><ApprovalCard ready={state==='AWAITING_APPROVAL'&&!screenshot} onApprove={()=>action.mutate({a:'approve',b:{approved_by:'demo-operator'}})} onReject={()=>action.mutate({a:'reject',b:{approved_by:'demo-operator'}})}/>{state==='APPROVED'&&<button className="primary pr" onClick={()=>action.mutate({a:'create-pr'})}><GitPullRequest/> Create approved PR report + evidence package</button>}<div className="safety-strip"><span><CheckCircle2/> Original source changed <b>NO</b></span><span><CheckCircle2/> Automatic deployment <b>NO</b></span><span><ShieldCheck/> Human approval required <b>YES</b></span></div></section>
 <div className="two"><Panel id="audit" icon={<Archive/>} title="Tamper-Evident Audit Package" subtitle="SHA-256 artifact hashes and chained event integrity"><div className="hashes"><span>First event hash <code>{screenshot?'12fa9c…8e41':pkg.data?.first_event_hash?.slice(0,16)||'Pending'}</code></span><span>Final audit-chain hash <code>{screenshot?'e8c410…117a':pkg.data?.final_audit_hash?.slice(0,16)||'Pending'}</code></span><span>Package hash <code>{screenshot?'1dd201…b9ce':pkg.data?.package_hash?.slice(0,16)||'Pending'}</code></span><strong>{screenshot||pkg.data?.verified?'✓ VERIFIED':'NOT YET GENERATED'}</strong></div><div className="export-actions"><a href={selected?api.downloadUrl(selected,'json'):'#'}><Download/> JSON</a><a href={selected?api.downloadUrl(selected,'report'):'#'}><Download/> Executive report</a><a href={selected?api.downloadUrl(selected,'bundle'):'#'}><Download/> ZIP bundle</a></div><small>Integrity evidence only — not blockchain, legal non-repudiation, or formal proof.</small></Panel><Panel id="scorecard" icon={<Activity/>} title="Reliability Scorecard" subtitle="Computed from persisted workflow events"><div className="score-grid">{Object.entries(screenshot?{claims_linked_to_evidence_pct:100,candidate_patches_compared:3,counterfactual_scenarios_tested:8,false_fix_detection_count:2,safety_policy_violations_blocked:2,original_source_tree_mutations:0,automatic_deployments:0,mandatory_approvals_bypassed:0}:scorecard.data||{}).slice(0,10).map(([k,v])=><div key={k}><span>{k.replaceAll('_',' ')}</span><b>{String(v)}</b></div>)}</div></Panel></div>
 </>}</main></div>}
function Panel({id,icon,title,subtitle,children}:{id:string;icon:React.ReactNode;title:string;subtitle:string;children:React.ReactNode}){return <section className="panel" id={id}><header><div className="panel-title">{icon}<div><h2>{title}</h2><p>{subtitle}</p></div></div><button className="evidence-btn">Show evidence</button></header>{children}</section>}
function Kpi({title,value,danger=false}:{title:string;value:string;danger?:boolean}){return <div className={`kpi ${danger?'danger':''}`}><span>{title}</span><b>{value}</b></div>}
function Node({kind,label}:{kind:string;label:string}){return <div className={`graph-node ${kind}`}><small>{kind}</small><b>{label}</b></div>}
function Empty({text}:{text:string}){return <div className="empty-state">{text}</div>}
